// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: router.proto

package router

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RouterClient is the client API for Router service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouterClient interface {
	GetOneInstanceWithPrefix(ctx context.Context, in *GetEndpointWithPrefixRequest, opts ...grpc.CallOption) (*GetOneInstanceResponse, error)
	SetRouteRule(ctx context.Context, in *SetRouteRuleRequest, opts ...grpc.CallOption) (*SetRouteRuleResponse, error)
}

type routerClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterClient(cc grpc.ClientConnInterface) RouterClient {
	return &routerClient{cc}
}

func (c *routerClient) GetOneInstanceWithPrefix(ctx context.Context, in *GetEndpointWithPrefixRequest, opts ...grpc.CallOption) (*GetOneInstanceResponse, error) {
	out := new(GetOneInstanceResponse)
	err := c.cc.Invoke(ctx, "/router.Router/GetOneInstanceWithPrefix", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) SetRouteRule(ctx context.Context, in *SetRouteRuleRequest, opts ...grpc.CallOption) (*SetRouteRuleResponse, error) {
	out := new(SetRouteRuleResponse)
	err := c.cc.Invoke(ctx, "/router.Router/SetRouteRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServer is the server API for Router service.
// All implementations must embed UnimplementedRouterServer
// for forward compatibility
type RouterServer interface {
	GetOneInstanceWithPrefix(context.Context, *GetEndpointWithPrefixRequest) (*GetOneInstanceResponse, error)
	SetRouteRule(context.Context, *SetRouteRuleRequest) (*SetRouteRuleResponse, error)
	mustEmbedUnimplementedRouterServer()
}

// UnimplementedRouterServer must be embedded to have forward compatible implementations.
type UnimplementedRouterServer struct {
}

func (UnimplementedRouterServer) GetOneInstanceWithPrefix(context.Context, *GetEndpointWithPrefixRequest) (*GetOneInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOneInstanceWithPrefix not implemented")
}
func (UnimplementedRouterServer) SetRouteRule(context.Context, *SetRouteRuleRequest) (*SetRouteRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRouteRule not implemented")
}
func (UnimplementedRouterServer) mustEmbedUnimplementedRouterServer() {}

// UnsafeRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouterServer will
// result in compilation errors.
type UnsafeRouterServer interface {
	mustEmbedUnimplementedRouterServer()
}

func RegisterRouterServer(s grpc.ServiceRegistrar, srv RouterServer) {
	s.RegisterService(&Router_ServiceDesc, srv)
}

func _Router_GetOneInstanceWithPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEndpointWithPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetOneInstanceWithPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/GetOneInstanceWithPrefix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetOneInstanceWithPrefix(ctx, req.(*GetEndpointWithPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_SetRouteRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRouteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).SetRouteRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/SetRouteRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).SetRouteRule(ctx, req.(*SetRouteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Router_ServiceDesc is the grpc.ServiceDesc for Router service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Router_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "router.Router",
	HandlerType: (*RouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOneInstanceWithPrefix",
			Handler:    _Router_GetOneInstanceWithPrefix_Handler,
		},
		{
			MethodName: "SetRouteRule",
			Handler:    _Router_SetRouteRule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "router.proto",
}
